CREATE BUFFERPOOL PLENORA_BP8K SIZE AUTOMATIC PAGESIZE 8K;

CREATE LARGE TABLESPACE PLENORA_TS8K
    PAGESIZE 8K
    MANAGED BY AUTOMATIC STORAGE
    BUFFERPOOL PLENORA_BP8K;

CREATE SCHEMA PLENORA_TEST;

CREATE TABLE PLENORA_TEST.CATALOG_PROBE (
    ID INTEGER NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    REV SMALLINT DEFAULT 0,
    NOTE VARCHAR(128),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_CATALOG_PROBE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX PLENORA_TEST.UQ_CATALOG_PROBE
    ON PLENORA_TEST.CATALOG_PROBE (CODE ASC, REV DESC);

CREATE VIEW PLENORA_TEST.CATALOG_PROBE_VIEW AS
    SELECT ID, CODE FROM PLENORA_TEST.CATALOG_PROBE;

CREATE TABLE PLENORA_TEST.READ_PROBE (
    ID INTEGER NOT NULL,
    FLAG BOOLEAN,
    COUNT_BIG BIGINT,
    AMOUNT DECIMAL(18, 4),
    RATIO DOUBLE,
    LABEL VARCHAR(128),
    CREATED_ON DATE,
    CREATED_AT TIMESTAMP,
    PAYLOAD VARCHAR(32) FOR BIT DATA,
    CONSTRAINT PK_READ_PROBE PRIMARY KEY (ID)
);

INSERT INTO PLENORA_TEST.READ_PROBE
    (ID, FLAG, COUNT_BIG, AMOUNT, RATIO, LABEL, CREATED_ON, CREATED_AT, PAYLOAD)
VALUES
    (1, TRUE, 9223372036854770000, 12345678901234.5678, 3.5,
     'alpha', DATE('2026-08-27'), TIMESTAMP('2026-08-27-12.34.56.123456'),
     BX'000102FF'),
    (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

CREATE TABLE PLENORA_TEST.TX_PROBE (
    ID INTEGER NOT NULL,
    VALUE VARCHAR(64) NOT NULL,
    VERSION INTEGER NOT NULL,
    CONSTRAINT PK_TX_PROBE PRIMARY KEY (ID)
);

CREATE TABLE PLENORA_TEST.WRITE_PROBE (
    ID INTEGER NOT NULL,
    VALUE VARCHAR(64),
    VERSION INTEGER NOT NULL,
    CONSTRAINT PK_WRITE_PROBE PRIMARY KEY (ID)
);

CREATE TABLE PLENORA_TEST.SPATIAL_PROBE (
    ID INTEGER NOT NULL,
    SHAPE ST_GEOMETRY,
    CONSTRAINT PK_SPATIAL_PROBE PRIMARY KEY (ID)
) IN PLENORA_TS8K;

INSERT INTO PLENORA_TEST.SPATIAL_PROBE (ID, SHAPE)
VALUES
    (1, ST_GEOMETRY('POINT (1 2)', 4326)),
    (2, ST_GEOMETRY('POLYGON ((0 0, 3 0, 3 3, 0 3, 0 0))', 4326)),
    (3, NULL),
    (4, ST_GEOMETRY('POINT Z (1 2 3)', 4326));
