"""Type stubs per il wrapper AsyncTransaction Python."""
from typing import Any

from ._native import AsyncTransaction as _NativeAsyncTransaction
from .async_query import (
    AsyncDelete,
    AsyncInsert,
    AsyncSelect,
    AsyncUpdate,
    AsyncUpsert,
)


class AsyncTransaction:
    def __init__(self, native: _NativeAsyncTransaction) -> None: ...
    async def is_active(self) -> bool: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def savepoint(self, name: str) -> None: ...
    async def rollback_to_savepoint(self, name: str) -> None: ...
    async def release_savepoint(self, name: str) -> None: ...
    async def __aenter__(self) -> AsyncTransaction: ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...
    def __repr__(self) -> str: ...
    async def execute(self, sql: str, params: list | None = None) -> int: ...
    async def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    async def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    def select(self, table: str, schema: str | None = None) -> AsyncSelect: ...
    def insert(self, table: str, schema: str | None = None) -> AsyncInsert: ...
    def update(self, table: str, schema: str | None = None) -> AsyncUpdate: ...
    def delete(self, table: str, schema: str | None = None) -> AsyncDelete: ...
    def upsert(self, table: str, schema: str | None = None) -> AsyncUpsert: ...
    async def _execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    async def _execute_portable_count(self, ast_json: str) -> int: ...
