"""Type stubs per il wrapper AsyncTransaction Python."""
from typing import Any, Mapping, overload

from ._native import AsyncTransaction as _NativeAsyncTransaction
from .async_query import (
    AsyncDelete,
    AsyncInsert,
    AsyncSelect,
    AsyncUpdate,
    AsyncUpsert,
)
from .expression import ExecutableStatement
from .result import MutationResult, Result
from .graph import GraphValue


class AsyncTransaction:
    def __init__(
        self, native: _NativeAsyncTransaction, provider: str = "postgres"
    ) -> None: ...
    async def is_active(self) -> bool: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def savepoint(self, name: str) -> None: ...
    async def rollback_to_savepoint(self, name: str) -> None: ...
    async def release_savepoint(self, name: str) -> None: ...
    async def conditional_update(
        self,
        update_sql: str,
        update_params: list | None = None,
        expected_affected_rows: int = 1,
        key_probe_sql: str | None = None,
        key_probe_params: list | None = None,
    ) -> None: ...
    async def __aenter__(self) -> AsyncTransaction: ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...
    def __repr__(self) -> str: ...
    @overload
    async def execute(self, sql: str, params: list | None = None) -> int: ...
    @overload
    async def execute(
        self, sql: ExecutableStatement, params: Mapping[str, Any] | None = None
    ) -> Result | int | MutationResult: ...
    async def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    async def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    async def cypher(
        self, graph: str, query: str, columns: list[str], params: dict[str, Any] | None = None
    ) -> list[dict[str, GraphValue]]: ...
    def select(self, table: str, schema: str | None = None) -> AsyncSelect: ...
    def insert(self, table: str, schema: str | None = None) -> AsyncInsert: ...
    def update(self, table: str, schema: str | None = None) -> AsyncUpdate: ...
    def delete(self, table: str, schema: str | None = None) -> AsyncDelete: ...
    def upsert(self, table: str, schema: str | None = None) -> AsyncUpsert: ...
    async def _execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    async def _execute_portable_count(self, ast_json: str) -> int: ...
