"""Type stubs per il wrapper AsyncSession Python."""
from typing import Any, Mapping, overload

from ._async_transaction import AsyncTransaction
from ._native import AsyncSession as _NativeAsyncSession, SessionContext
from .async_query import (
    AsyncDelete,
    AsyncInsert,
    AsyncSelect,
    AsyncUpdate,
    AsyncUpsert,
)
from .expression import ExecutableStatement
from .result import MutationResult, Result
from .graph import GraphValue


class AsyncSession:
    def __init__(self, native: _NativeAsyncSession) -> None: ...
    @property
    def server_version(self) -> str: ...
    @property
    def capabilities(self) -> dict: ...
    @property
    def postgis_version(self) -> str | None: ...
    @property
    def age_version(self) -> str | None: ...
    async def age_capabilities(self) -> dict: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def metrics(self) -> dict: ...
    async def __aenter__(self) -> AsyncSession: ...
    async def __aexit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    @overload
    async def execute(self, sql: str, params: list | None = None) -> int: ...
    @overload
    async def execute(
        self, sql: ExecutableStatement, params: Mapping[str, Any] | None = None
    ) -> Result | int | MutationResult: ...
    async def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    async def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    async def cypher(
        self, graph: str, query: str, columns: list[str], params: dict[str, Any] | None = None
    ) -> list[dict[str, GraphValue]]: ...
    async def execute_ddl(self, sql: str) -> None: ...
    @property
    def inspect(self) -> _AsyncInspector: ...
    async def begin(
        self,
        isolation: str | None = None,
        read_only: bool | None = None,
        deferrable: bool | None = None,
        statement_timeout_ms: int | None = None,
        context: SessionContext | None = None,
        native_query_policy: str | None = None,
    ) -> AsyncTransaction: ...
    def select(self, table: str, schema: str | None = None) -> AsyncSelect: ...
    def insert(self, table: str, schema: str | None = None) -> AsyncInsert: ...
    def update(self, table: str, schema: str | None = None) -> AsyncUpdate: ...
    def delete(self, table: str, schema: str | None = None) -> AsyncDelete: ...
    def upsert(self, table: str, schema: str | None = None) -> AsyncUpsert: ...
    async def aread(
        self,
        schema: str,
        object: str,
        *,
        projection: list[str] | None = None,
        order_by: list[tuple[str, str]] | None = None,
        limit: int | None = None,
    ) -> Any: ...
    async def acopy_from(
        self,
        schema: str,
        table: str,
        source: Any,
        *,
        mode: str = "append",
        transaction_profile: str = "single_transaction",
        mapping_policy: str = "compatible",
        keys: list[str] | None = None,
        update_columns: list[str] | None = None,
    ) -> dict: ...
    async def _execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    async def _execute_portable_count(self, ast_json: str) -> int: ...


class _AsyncInspector:
    def __init__(self, native: _NativeAsyncSession) -> None: ...
    async def catalogs(self) -> list[str]: ...
    async def schemas(self) -> list[str]: ...
    async def tables(self, schema: str) -> list[dict]: ...
    async def describe(self, schema: str, table: str) -> dict: ...
