"""Type stubs per il wrapper AsyncSession Python."""
from typing import Any

from ._async_transaction import AsyncTransaction
from ._native import AsyncSession as _NativeAsyncSession
from .async_query import (
    AsyncDelete,
    AsyncInsert,
    AsyncSelect,
    AsyncUpdate,
    AsyncUpsert,
)


class AsyncSession:
    def __init__(self, native: _NativeAsyncSession) -> None: ...
    @property
    def server_version(self) -> str: ...
    @property
    def postgis_version(self) -> str | None: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    async def __aenter__(self) -> AsyncSession: ...
    async def __aexit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    async def execute(self, sql: str, params: list | None = None) -> int: ...
    async def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    async def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    async def begin(
        self,
        isolation: str | None = None,
        read_only: bool | None = None,
        deferrable: bool | None = None,
        statement_timeout_ms: int | None = None,
    ) -> AsyncTransaction: ...
    def select(self, table: str, schema: str | None = None) -> AsyncSelect: ...
    def insert(self, table: str, schema: str | None = None) -> AsyncInsert: ...
    def update(self, table: str, schema: str | None = None) -> AsyncUpdate: ...
    def delete(self, table: str, schema: str | None = None) -> AsyncDelete: ...
    def upsert(self, table: str, schema: str | None = None) -> AsyncUpsert: ...
    async def aread(self, schema: str, object: str) -> Any: ...
    async def acopy_from(
        self,
        schema: str,
        table: str,
        source: Any,
        *,
        mode: str = "append",
        transaction_profile: str = "single_transaction",
    ) -> dict: ...
    async def _execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    async def _execute_portable_count(self, ast_json: str) -> int: ...
