from typing import Any, Callable, Generic, TypeVar

from ._async_session import AsyncSession
from ._native import AsyncEngine as _NativeAsyncEngine
from ._native import Engine as _NativeEngine
from ._session import Session

SessionT = TypeVar("SessionT")

class Engine(Generic[SessionT]):
    def __init__(
        self,
        native: _NativeEngine,
        wrap_session: Callable[[Any], SessionT] | None = None,
    ) -> None: ...
    @property
    def provider_kind(self) -> str: ...
    @property
    def is_disposed(self) -> bool: ...
    def session(self) -> SessionT: ...
    def statistics(self) -> dict: ...
    def dispose(self) -> None: ...
    def __enter__(self) -> Engine[SessionT]: ...
    def __exit__(self, *_args: Any) -> bool: ...
    def __repr__(self) -> str: ...

class AsyncEngine(Generic[SessionT]):
    def __init__(
        self,
        native: _NativeAsyncEngine,
        wrap_session: Callable[[Any], SessionT] | None = None,
    ) -> None: ...
    @property
    def provider_kind(self) -> str: ...
    @property
    def is_disposed(self) -> bool: ...
    def session(self) -> SessionT: ...
    def statistics(self) -> dict: ...
    def dispose(self) -> None: ...
    async def __aenter__(self) -> AsyncEngine[SessionT]: ...
    async def __aexit__(self, *_args: Any) -> bool: ...
    def __repr__(self) -> str: ...
