from typing import Any, Callable, Generic, TypeVar

from ._async_session import AsyncSession
from ._native import AsyncEngine as _NativeAsyncEngine
from ._native import Engine as _NativeEngine
from ._session import Session
from .metadata import MetaData

SessionT = TypeVar("SessionT")

class Engine(Generic[SessionT]):
    def __init__(
        self,
        native: _NativeEngine,
        wrap_session: Callable[[Any], SessionT] | None = None,
    ) -> None: ...
    @property
    def provider_kind(self) -> str: ...
    @property
    def is_disposed(self) -> bool: ...
    @property
    def metadata_cache_entries(self) -> int: ...
    def session(self) -> SessionT: ...
    def statistics(self) -> dict: ...
    def reflect_table(
        self, schema: str | None, table: str, *,
        catalog: str | None = ..., refresh: bool = ...,
    ) -> MetaData: ...
    def invalidate_metadata(
        self, schema: str | None = ..., table: str | None = ...,
        *, catalog: str | None = ...,
    ) -> int: ...
    def dispose(self) -> None: ...
    def __enter__(self) -> Engine[SessionT]: ...
    def __exit__(self, *_args: Any) -> bool: ...
    def __repr__(self) -> str: ...

class AsyncEngine(Generic[SessionT]):
    def __init__(
        self,
        native: _NativeAsyncEngine,
        wrap_session: Callable[[Any], SessionT] | None = None,
    ) -> None: ...
    @property
    def provider_kind(self) -> str: ...
    @property
    def is_disposed(self) -> bool: ...
    @property
    def metadata_cache_entries(self) -> int: ...
    def session(self) -> SessionT: ...
    def statistics(self) -> dict: ...
    async def reflect_table(
        self, schema: str | None, table: str, *,
        catalog: str | None = ..., refresh: bool = ...,
    ) -> MetaData: ...
    def invalidate_metadata(
        self, schema: str | None = ..., table: str | None = ...,
        *, catalog: str | None = ...,
    ) -> int: ...
    def dispose(self) -> None: ...
    async def __aenter__(self) -> AsyncEngine[SessionT]: ...
    async def __aexit__(self, *_args: Any) -> bool: ...
    def __repr__(self) -> str: ...
