from typing import Any

from ._async_session import AsyncSession
from ._native import AsyncEngine as _NativeAsyncEngine
from ._native import Engine as _NativeEngine
from ._session import Session

class Engine:
    def __init__(self, native: _NativeEngine) -> None: ...
    @property
    def provider_kind(self) -> str: ...
    @property
    def is_disposed(self) -> bool: ...
    def session(self) -> Session: ...
    def statistics(self) -> dict: ...
    def dispose(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, *_args: Any) -> bool: ...
    def __repr__(self) -> str: ...

class AsyncEngine:
    def __init__(self, native: _NativeAsyncEngine) -> None: ...
    @property
    def provider_kind(self) -> str: ...
    @property
    def is_disposed(self) -> bool: ...
    def session(self) -> AsyncSession: ...
    def statistics(self) -> dict: ...
    def dispose(self) -> None: ...
    async def __aenter__(self) -> AsyncEngine: ...
    async def __aexit__(self, *_args: Any) -> bool: ...
    def __repr__(self) -> str: ...
