"""Type stubs per il modulo nativo PyO3 (`plenora_database._native`).

Questi stubs descrivono l'interfaccia esposta dal modulo Rust compilato
via maturin. Non c'è auto-generazione con pyo3 0.23 con abi3, quindi
li manteniamo manualmente. Consumer usa i re-export dal top-level
`plenora_database` (vedi `__init__.pyi`).
"""
from typing import Any

# ============================ Functions ============================

def version() -> str: ...

def connect(dsn: str) -> Session: ...

def aconnect(dsn: str) -> Any:  # awaitable → AsyncSession
    ...

# ============================ Session (sync) ============================

class Session:
    @property
    def server_version(self) -> str: ...
    @property
    def postgis_version(self) -> str | None: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
    def __repr__(self) -> str: ...
    def execute(self, sql: str, params: list | None = None) -> int: ...
    def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    def execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    def execute_portable_count(self, ast_json: str) -> int: ...
    def begin(
        self,
        isolation: str | None = None,
        read_only: bool | None = None,
        deferrable: bool | None = None,
        statement_timeout_ms: int | None = None,
    ) -> Transaction: ...

# ============================ Transaction (sync) ============================

class Transaction:
    @property
    def is_active(self) -> bool: ...
    def execute(self, sql: str, params: list | None = None) -> int: ...
    def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    def execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    def execute_portable_count(self, ast_json: str) -> int: ...
    def savepoint(self, name: str) -> None: ...
    def rollback_to_savepoint(self, name: str) -> None: ...
    def release_savepoint(self, name: str) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
    def __repr__(self) -> str: ...

# ============================ AsyncSession ============================

class AsyncSession:
    @property
    def server_version(self) -> str: ...
    @property
    def postgis_version(self) -> str | None: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def __aenter__(self) -> Any: ...  # awaitable → AsyncSession
    def __aexit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> Any: ...  # awaitable → bool
    def __repr__(self) -> str: ...
    def execute(self, sql: str, params: list | None = None) -> Any: ...  # awaitable → int
    def execute_scalar(
        self, sql: str, params: list | None = None
    ) -> Any: ...  # awaitable → Any
    def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> Any: ...  # awaitable → list[dict]
    def execute_portable_rows(self, ast_json: str) -> Any: ...  # awaitable → list[dict]
    def execute_portable_count(self, ast_json: str) -> Any: ...  # awaitable → int
    def begin(
        self,
        isolation: str | None = None,
        read_only: bool | None = None,
        deferrable: bool | None = None,
        statement_timeout_ms: int | None = None,
    ) -> Any: ...  # awaitable → AsyncTransaction

# ============================ AsyncTransaction ============================

class AsyncTransaction:
    @property
    def is_active(self) -> Any: ...  # awaitable → bool (nota: lock async)
    def execute(self, sql: str, params: list | None = None) -> Any: ...  # awaitable → int
    def execute_scalar(
        self, sql: str, params: list | None = None
    ) -> Any: ...  # awaitable → Any
    def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> Any: ...  # awaitable → list[dict]
    def execute_portable_rows(self, ast_json: str) -> Any: ...  # awaitable → list[dict]
    def execute_portable_count(self, ast_json: str) -> Any: ...  # awaitable → int
    def savepoint(self, name: str) -> Any: ...  # awaitable → None
    def rollback_to_savepoint(self, name: str) -> Any: ...  # awaitable → None
    def release_savepoint(self, name: str) -> Any: ...  # awaitable → None
    def commit(self) -> Any: ...  # awaitable → None
    def rollback(self) -> Any: ...  # awaitable → None
    def __aenter__(self) -> Any: ...  # awaitable → AsyncTransaction
    def __aexit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> Any: ...  # awaitable → bool
    def __repr__(self) -> str: ...

# ============================ Exception hierarchy ============================

class PlenoraError(RuntimeError):
    category: str
    phase: str
    retry: str
    remote_effect: str
    provider: str | None
    execution_id: str | None
    diagnostics: dict | list | None

class PlenoraInvalidPlanError(PlenoraError): ...
class PlenoraInvalidConfigurationError(PlenoraError): ...
class PlenoraSchemaError(PlenoraError): ...
class PlenoraDataMappingError(PlenoraError): ...
class PlenoraCrsError(PlenoraError): ...
class PlenoraUnsupportedError(PlenoraError): ...
class PlenoraNotFoundError(PlenoraError): ...
class PlenoraConflictError(PlenoraError): ...
class PlenoraConcurrentModificationError(PlenoraError): ...
class PlenoraAuthenticationError(PlenoraError): ...
class PlenoraAuthorizationError(PlenoraError): ...
class PlenoraTimeoutError(PlenoraError): ...
class PlenoraCancelledError(PlenoraError): ...
class PlenoraResourceLimitError(PlenoraError): ...
class PlenoraIoError(PlenoraError): ...
class PlenoraProtocolError(PlenoraError): ...
class PlenoraTransientError(PlenoraError): ...
class PlenoraExecutionError(PlenoraError): ...
class PlenoraInternalError(PlenoraError): ...
