"""Type stubs per il wrapper Session Python."""
from typing import Any

from ._native import Session as _NativeSession, SessionContext
from ._transaction import Transaction
from .query import Delete, Insert, Select, Update, Upsert


class Session:
    def __init__(self, native: _NativeSession) -> None: ...
    @property
    def server_version(self) -> str: ...
    @property
    def postgis_version(self) -> str | None: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def execute(self, sql: str, params: list | None = None) -> int: ...
    def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    def execute_ddl(self, sql: str) -> None: ...
    def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    def begin(
        self,
        isolation: str | None = None,
        read_only: bool | None = None,
        deferrable: bool | None = None,
        statement_timeout_ms: int | None = None,
        context: SessionContext | None = None,
        native_query_policy: str | None = None,
    ) -> Transaction: ...
    def metrics(self) -> dict: ...
    @property
    def inspect(self) -> _Inspector: ...
    def select(self, table: str, schema: str | None = None) -> Select: ...
    def insert(self, table: str, schema: str | None = None) -> Insert: ...
    def update(self, table: str, schema: str | None = None) -> Update: ...
    def delete(self, table: str, schema: str | None = None) -> Delete: ...
    def upsert(self, table: str, schema: str | None = None) -> Upsert: ...
    def read(
        self,
        schema: str,
        object: str,
        *,
        projection: list[str] | None = None,
        order_by: list[tuple[str, str]] | None = None,
        limit: int | None = None,
    ) -> Any: ...
    def copy_from(
        self,
        schema: str,
        table: str,
        source: Any,
        *,
        mode: str = "append",
        transaction_profile: str = "single_transaction",
        mapping_policy: str = "compatible",
        keys: list[str] | None = None,
        update_columns: list[str] | None = None,
    ) -> dict: ...
    def _execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    def _execute_portable_count(self, ast_json: str) -> int: ...


class _Inspector:
    def __init__(self, native: _NativeSession) -> None: ...
    def catalogs(self) -> list[str]: ...
    def schemas(self) -> list[str]: ...
    def tables(self, schema: str) -> list[dict]: ...
    def describe(self, schema: str, table: str) -> dict: ...
