"""Type stubs per il wrapper Transaction Python."""
from typing import Any, Mapping, overload

from ._native import Transaction as _NativeTransaction
from .expression import ExecutableStatement
from .query import Delete, Insert, Select, Update, Upsert
from .result import MutationResult, Result
from .graph import GraphValue


class Transaction:
    def __init__(self, native: _NativeTransaction, provider: str = "postgres") -> None: ...
    @property
    def is_active(self) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def savepoint(self, name: str) -> None: ...
    def rollback_to_savepoint(self, name: str) -> None: ...
    def release_savepoint(self, name: str) -> None: ...
    def conditional_update(
        self,
        update_sql: str,
        update_params: list | None = None,
        expected_affected_rows: int = 1,
        key_probe_sql: str | None = None,
        key_probe_params: list | None = None,
    ) -> None: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...
    def __repr__(self) -> str: ...
    @overload
    def execute(self, sql: str, params: list | None = None) -> int: ...
    @overload
    def execute(
        self, sql: ExecutableStatement, params: Mapping[str, Any] | None = None
    ) -> Result | int | MutationResult: ...
    def execute_scalar(self, sql: str, params: list | None = None) -> Any: ...
    def execute_returning_rows(
        self, sql: str, params: list | None = None
    ) -> list[dict]: ...
    def cypher(
        self,
        graph: str,
        query: str,
        columns: list[str],
        params: dict[str, Any] | None = None,
        *,
        max_rows: int = 10_000,
    ) -> list[dict[str, GraphValue]]: ...
    def select(self, table: str, schema: str | None = None) -> Select: ...
    def insert(self, table: str, schema: str | None = None) -> Insert: ...
    def update(self, table: str, schema: str | None = None) -> Update: ...
    def delete(self, table: str, schema: str | None = None) -> Delete: ...
    def upsert(self, table: str, schema: str | None = None) -> Upsert: ...
    def _execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    def _execute_portable_count(self, ast_json: str) -> int: ...
