from collections.abc import AsyncIterator, Awaitable, Callable
from typing import Any

class DatabaseASGIMiddleware:
    def __init__(self, app: Callable[..., Awaitable[None]], engine: Any, *, state_key: str = "database") -> None: ...
    async def __call__(self, scope: dict, receive: Any, send: Any) -> None: ...

def session_dependency(engine: Any) -> Callable[[], AsyncIterator[Any]]: ...
