from dataclasses import dataclass
from typing import Any
from ._engine import AsyncEngine, Engine
from .protocols import AsyncSessionProtocol, SessionProtocol

@dataclass(frozen=True)
class PoolConfig:
    max_connections: int = ...
    acquire_timeout_ms: int = ...
    def __post_init__(self) -> None: ...

@dataclass(frozen=True)
class EngineConfig:
    provider: str
    host: str | None = ...
    database: str | None = ...
    user: str | None = ...
    password: str | None = ...
    port: int | None = ...
    tls_mode: str = ...
    tls_ca: str | None = ...
    pool: PoolConfig | None = ...
    _raw_url: str | None = ...
    def __post_init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @classmethod
    def from_url(cls, value: str) -> EngineConfig: ...
    @classmethod
    def from_postgres_dsn(
        cls, dsn: str, *, tls_mode: str = ...,
        pool: PoolConfig | None = ...,
    ) -> EngineConfig: ...

def engine_from_url(value: str | EngineConfig) -> Engine[SessionProtocol]: ...
async def async_engine_from_url(
    value: str | EngineConfig,
) -> AsyncEngine[AsyncSessionProtocol]: ...
