from collections.abc import Iterator
from enum import Enum
from typing import Any, Iterable, Self

class Expression:
    def label(self, name: str) -> Label: ...
    def asc(self) -> Ordering: ...
    def desc(self) -> Ordering: ...
    def in_(self, *values: Expression) -> Predicate: ...
    def not_in(self, *values: Expression) -> Predicate: ...
    def between(self, lower: Expression, upper: Expression) -> Predicate: ...
    def not_between(self, lower: Expression, upper: Expression) -> Predicate: ...
    def like(self, pattern: Expression) -> Predicate: ...
    def ilike(self, pattern: Expression) -> Predicate: ...
    def not_like(self, pattern: Expression) -> Predicate: ...
    def not_ilike(self, pattern: Expression) -> Predicate: ...
    def in_subquery(self, statement: SelectStatement) -> Predicate: ...
    def not_in_subquery(self, statement: SelectStatement) -> Predicate: ...
    def is_null(self) -> Predicate: ...
    def is_not_null(self) -> Predicate: ...
    def __eq__(self, other: object) -> Predicate: ...
    def __ne__(self, other: object) -> Predicate: ...
    def __lt__(self, other: Expression) -> Predicate: ...
    def __le__(self, other: Expression) -> Predicate: ...
    def __gt__(self, other: Expression) -> Predicate: ...
    def __ge__(self, other: Expression) -> Predicate: ...
    def __bool__(self) -> bool: ...

class ExecutableStatement: ...

class BindType(str, Enum):
    BOOLEAN: BindType
    INTEGER: BindType
    BIG_INTEGER: BindType
    FLOAT: BindType
    STRING: BindType
    BINARY: BindType
    DATE: BindType
    TIMESTAMP: BindType

class UnboundColumn(Expression):
    name: str
    def __post_init__(self) -> None: ...

class Column(Expression):
    table: Table
    name: str
    metadata: Any | None
    def __post_init__(self) -> None: ...

class BindParameter(Expression):
    name: str
    type_: BindType
    def __post_init__(self) -> None: ...

class Wildcard(Expression):
    table: Table | None

class Label(Expression):
    expression: Expression
    name: str

class FunctionExpression(Expression):
    function: str
    arguments: tuple[Expression, ...]
    def over(
        self, *, partition_by: Iterable[Expression] = ...,
        order_by: Iterable[Expression | Ordering] = ...,
        rows: tuple[int | None, int | None] | None = ...,
        range_: tuple[int | None, int | None] | None = ...,
        groups: tuple[int | None, int | None] | None = ...,
    ) -> WindowExpression: ...

class WindowExpression(Expression):
    function: str
    arguments: tuple[Expression, ...]
    partition_by: tuple[Expression, ...]
    order_by: tuple[Ordering, ...]
    frame: dict[str, Any] | None

class ScalarSubquery(Expression):
    statement: SelectStatement

class Predicate(Expression):
    def __and__(self, other: Predicate) -> Predicate: ...
    def __or__(self, other: Predicate) -> Predicate: ...
    def __invert__(self) -> Predicate: ...

class Ordering:
    expression: Expression
    direction: str
    def __post_init__(self) -> None: ...

class ColumnCollection:
    def __init__(self, columns: tuple[Column, ...]) -> None: ...
    def __getattr__(self, name: str) -> Column: ...
    def __getitem__(self, name: str) -> Column: ...
    def __iter__(self) -> Iterator[Column]: ...

class Table:
    name: str
    schema: str | None
    catalog: str | None
    alias_name: str | None
    columns: tuple[Column, ...]
    c: ColumnCollection
    metadata: Any | None
    def __init__(
        self, name: str, columns: tuple[str | UnboundColumn, ...], *,
        schema: str | None = ..., catalog: str | None = ...,
        alias_name: str | None = ...,
    ) -> None: ...
    @property
    def qualifier(self) -> str: ...
    @property
    def star(self) -> Wildcard: ...
    def alias(self, name: str) -> Table: ...

class DerivedTable:
    statement: SelectStatement
    alias_name: str
    columns: tuple[Column, ...]
    c: ColumnCollection
    def __init__(
        self, statement: SelectStatement, alias_name: str,
        column_names: Iterable[str],
    ) -> None: ...
    @property
    def qualifier(self) -> str: ...
    @property
    def star(self) -> Wildcard: ...

class CommonTable:
    statement: SelectStatement
    name: str
    recursive: bool
    columns: tuple[Column, ...]
    c: ColumnCollection
    def __init__(
        self, statement: SelectStatement, name: str,
        column_names: Iterable[str], *, recursive: bool = ...,
    ) -> None: ...
    @property
    def qualifier(self) -> str: ...
    @property
    def star(self) -> Wildcard: ...

class SelectStatement(ExecutableStatement):
    projections: tuple[Expression, ...]
    source: Table | DerivedTable | CommonTable | None
    def __post_init__(self) -> None: ...
    def select_from(self, source: Table | DerivedTable | CommonTable) -> Self: ...
    def join(
        self, right: Table | DerivedTable | CommonTable,
        on: Predicate | None = ..., *, kind: str = "inner",
    ) -> Self: ...
    def where(self, predicate: Predicate) -> Self: ...
    def group_by(self, *expressions: Expression) -> Self: ...
    def having(self, predicate: Predicate) -> Self: ...
    def order_by(self, *values: Expression | Ordering) -> Self: ...
    def limit(self, value: int) -> Self: ...
    def offset(self, value: int) -> Self: ...
    def distinct(self) -> Self: ...
    def subquery(self, name: str, *column_names: str) -> DerivedTable: ...
    def cte(
        self, name: str, *column_names: str, recursive: bool = ...,
    ) -> CommonTable: ...
    def scalar_subquery(self) -> ScalarSubquery: ...
    def exists(self) -> Predicate: ...
    def union(self, other: SelectStatement, *, all: bool = ...) -> Self: ...
    def intersect(self, other: SelectStatement, *, all: bool = ...) -> Self: ...
    def except_(self, other: SelectStatement, *, all: bool = ...) -> Self: ...
    def to_ast(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class InsertStatement(ExecutableStatement):
    target: Table
    columns: tuple[str, ...]
    rows: tuple[tuple[Expression, ...], ...]
    returning_names: tuple[str, ...]
    def values(self, **values: Expression) -> Self: ...
    def returning(self, *columns: Column) -> Self: ...
    def to_ast(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class UpdateStatement(ExecutableStatement):
    target: Table
    assignments: tuple[tuple[str, Expression], ...]
    predicate: Predicate | None
    returning_names: tuple[str, ...]
    def values(self, **values: Expression) -> Self: ...
    def where(self, predicate: Predicate) -> Self: ...
    def returning(self, *columns: Column) -> Self: ...
    def to_ast(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class DeleteStatement(ExecutableStatement):
    target: Table
    predicate: Predicate | None
    returning_names: tuple[str, ...]
    def where(self, predicate: Predicate) -> Self: ...
    def returning(self, *columns: Column) -> Self: ...
    def to_ast(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class UpsertStatement(ExecutableStatement):
    target: Table
    columns: tuple[str, ...]
    rows: tuple[tuple[Expression, ...], ...]
    conflict_names: tuple[str, ...]
    assignments: tuple[tuple[str, Expression], ...]
    returning_names: tuple[str, ...]
    def values(self, **values: Expression) -> Self: ...
    def on_conflict(self, *columns: Column) -> Self: ...
    def set(self, **values: Expression) -> Self: ...
    def returning(self, *columns: Column) -> Self: ...
    def to_ast(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

def column(name: str) -> UnboundColumn: ...
def table(
    name: str, *columns: str | UnboundColumn,
    schema: str | None = ..., catalog: str | None = ...,
) -> Table: ...
def bind(name: str, type_: BindType) -> BindParameter: ...
def select(*expressions: Expression) -> SelectStatement: ...
def insert(target: Table) -> InsertStatement: ...
def update(target: Table) -> UpdateStatement: ...
def delete(target: Table) -> DeleteStatement: ...
def upsert(target: Table) -> UpsertStatement: ...
def and_(*predicates: Predicate) -> Predicate: ...
def or_(*predicates: Predicate) -> Predicate: ...

class FunctionNamespace:
    def __getattr__(self, name: str) -> Any: ...
    def lower(self, expression: Expression) -> FunctionExpression: ...
    def upper(self, expression: Expression) -> FunctionExpression: ...
    def coalesce(self, *expressions: Expression) -> FunctionExpression: ...
    def count(self, expression: Expression = ...) -> FunctionExpression: ...
    def sum(self, expression: Expression) -> FunctionExpression: ...
    def avg(self, expression: Expression) -> FunctionExpression: ...
    def min(self, expression: Expression) -> FunctionExpression: ...
    def max(self, expression: Expression) -> FunctionExpression: ...
    def row_number(self) -> FunctionExpression: ...
    def rank(self) -> FunctionExpression: ...
    def dense_rank(self) -> FunctionExpression: ...
    def lag(self, *expressions: Expression) -> FunctionExpression: ...
    def lead(self, *expressions: Expression) -> FunctionExpression: ...

func: FunctionNamespace
