from collections.abc import Iterator
from typing import Any, Self

class Expression:
    def label(self, name: str) -> Label: ...
    def asc(self) -> Ordering: ...
    def desc(self) -> Ordering: ...
    def __eq__(self, other: object) -> Predicate: ...
    def __ne__(self, other: object) -> Predicate: ...
    def __lt__(self, other: Expression) -> Predicate: ...
    def __le__(self, other: Expression) -> Predicate: ...
    def __gt__(self, other: Expression) -> Predicate: ...
    def __ge__(self, other: Expression) -> Predicate: ...
    def __bool__(self) -> bool: ...

class UnboundColumn(Expression):
    name: str
    def __post_init__(self) -> None: ...

class Column(Expression):
    table: Table
    name: str
    def __post_init__(self) -> None: ...

class BindParameter(Expression):
    name: str
    def __post_init__(self) -> None: ...

class Wildcard(Expression):
    table: Table | None

class Label(Expression):
    expression: Expression
    name: str

class Predicate(Expression):
    def __and__(self, other: Predicate) -> Predicate: ...
    def __or__(self, other: Predicate) -> Predicate: ...
    def __invert__(self) -> Predicate: ...

class Ordering:
    expression: Expression
    direction: str
    def __post_init__(self) -> None: ...

class ColumnCollection:
    def __init__(self, columns: tuple[Column, ...]) -> None: ...
    def __getattr__(self, name: str) -> Column: ...
    def __getitem__(self, name: str) -> Column: ...
    def __iter__(self) -> Iterator[Column]: ...

class Table:
    name: str
    schema: str | None
    catalog: str | None
    alias_name: str | None
    columns: tuple[Column, ...]
    c: ColumnCollection
    def __init__(
        self, name: str, columns: tuple[str | UnboundColumn, ...], *,
        schema: str | None = ..., catalog: str | None = ...,
        alias_name: str | None = ...,
    ) -> None: ...
    @property
    def qualifier(self) -> str: ...
    @property
    def star(self) -> Wildcard: ...
    def alias(self, name: str) -> Table: ...

class SelectStatement:
    projections: tuple[Expression, ...]
    source: Table | None
    def __post_init__(self) -> None: ...
    def select_from(self, source: Table) -> Self: ...
    def join(self, right: Table, on: Predicate | None = ..., *, kind: str = "inner") -> Self: ...
    def where(self, predicate: Predicate) -> Self: ...
    def order_by(self, *values: Expression | Ordering) -> Self: ...
    def limit(self, value: int) -> Self: ...
    def offset(self, value: int) -> Self: ...
    def distinct(self) -> Self: ...
    def to_ast(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

def column(name: str) -> UnboundColumn: ...
def table(
    name: str, *columns: str | UnboundColumn,
    schema: str | None = ..., catalog: str | None = ...,
) -> Table: ...
def bind(name: str) -> BindParameter: ...
def select(*expressions: Expression) -> SelectStatement: ...
def and_(*predicates: Predicate) -> Predicate: ...
def or_(*predicates: Predicate) -> Predicate: ...
