from collections.abc import AsyncIterator, Iterable, Iterator, Mapping, MutableSequence
from dataclasses import dataclass
from enum import Enum
from types import TracebackType
from typing import Any, Generic, TypeVar, overload

from .expression import Column, Expression, Ordering, Predicate, Table
from .errors import PlenoraError
from .spatial import SpatialReference

T = TypeVar("T")  # noqa: PYI001

class OrmError(PlenoraError): ...
class OrmMappingError(OrmError): ...
class OrmStateError(OrmError): ...
class StaleObjectError(OrmError): ...
class OrmUnsupportedError(OrmError): ...

class ObjectState(str, Enum):
    TRANSIENT: ObjectState
    PENDING: ObjectState
    PERSISTENT: ObjectState
    DELETED: ObjectState
    DETACHED: ObjectState

@dataclass(frozen=True, slots=True)
class Geometry:
    srid: int
    dimensions: str
    semantics: str
    geometry_type: str | None
    def __post_init__(self) -> None: ...
    def validate(
        self, value: bytes | bytearray | SpatialReference
    ) -> SpatialReference: ...
    def bind(self, name: str) -> Expression: ...
    def predicate(
        self,
        function: str,
        column: Column,
        reference: Expression,
        distance: Expression | None = None,
    ) -> Predicate: ...
    def function(
        self, function: str, column: Column, *arguments: Expression
    ) -> Expression: ...

@dataclass(frozen=True, slots=True)
class BigInteger: ...

BIGINT: BigInteger

@dataclass(frozen=True, slots=True)
class String:
    length: int | None = ...
    def __post_init__(self) -> None: ...

@dataclass(frozen=True, slots=True)
class Numeric:
    precision: int = ...
    scale: int = ...
    def __post_init__(self) -> None: ...

@dataclass(frozen=True, slots=True)
class Uuid: ...

@dataclass(frozen=True, slots=True)
class Json: ...

@dataclass(frozen=True, slots=True)
class DateTime:
    timezone: bool = ...

UUID: Uuid
JSON: Json

@dataclass(frozen=True, slots=True)
class ServerDefault:
    kind: str
    value: Any
    def __post_init__(self) -> None: ...
    @classmethod
    def literal(cls, value: str | int | float | bool) -> ServerDefault: ...
    @classmethod
    def current_timestamp(cls) -> ServerDefault: ...

@dataclass(frozen=True, slots=True)
class UniqueConstraint:
    columns: tuple[str, ...]
    name: str | None
    def __init__(self, *columns: str, name: str | None = None) -> None: ...

@dataclass(frozen=True, slots=True)
class CheckConstraint:
    column: str
    operator: str
    value: str | int | float | bool
    name: str
    def __post_init__(self) -> None: ...
    @property
    def columns(self) -> tuple[str, ...]: ...

@dataclass(frozen=True, slots=True)
class OrmIndex:
    columns: tuple[str, ...]
    name: str
    unique: bool
    def __init__(
        self, *columns: str, name: str, unique: bool = False
    ) -> None: ...

@dataclass(frozen=True, slots=True)
class ForeignKeyConstraint:
    columns: tuple[str, ...]
    target: type[DeclarativeBase] | str
    target_columns: tuple[str, ...]
    name: str | None
    on_delete: str | None
    on_update: str | None
    def __init__(
        self,
        columns: Iterable[str],
        target: type[DeclarativeBase] | str,
        target_columns: Iterable[str],
        *,
        name: str | None = None,
        on_delete: str | None = None,
        on_update: str | None = None,
    ) -> None: ...

@dataclass(frozen=True, slots=True)
class InstanceInspection:
    state: ObjectState
    identity: tuple[Any, ...] | None
    dirty: tuple[str, ...]

class MappedColumn(Generic[T]):
    type_: Any | None
    primary_key: bool
    version: bool
    nullable: bool
    generated: bool
    server_default: bool
    server_default_spec: ServerDefault | None
    unique: bool
    name: str | None
    column: Column | None
    def __init__(
        self,
        type_: Any | None = None,
        *,
        primary_key: bool = False,
        version: bool = False,
        nullable: bool = True,
        generated: bool = False,
        server_default: bool | ServerDefault = False,
        unique: bool = False,
    ) -> None: ...
    @overload
    def __get__(self, instance: None, owner: type | None = None) -> Column: ...
    @overload
    def __get__(self, instance: object, owner: type | None = None) -> T | None: ...
    def __set__(self, instance: object, value: T | None) -> None: ...

Mapped = MappedColumn

def mapped_column(
    type_: Any | None = None,
    *,
    primary_key: bool = False,
    version: bool = False,
    nullable: bool = True,
    generated: bool = False,
    server_default: bool | ServerDefault = False,
    unique: bool = False,
) -> MappedColumn[Any]: ...

class Mapper:
    model: type[DeclarativeBase]
    table: Table
    attributes: tuple[MappedColumn[Any], ...]
    primary_key: MappedColumn[Any]
    primary_keys: tuple[MappedColumn[Any], ...]
    version: MappedColumn[Any] | None
    relationships: tuple[Relationship[Any], ...]
    constraints: tuple[
        UniqueConstraint | CheckConstraint | OrmIndex | ForeignKeyConstraint, ...
    ]
    inherits: Mapper | None
    inheritance: str
    local_attributes: tuple[MappedColumn[Any], ...]
    polymorphic_identity: Any
    polymorphic_on: str | None
    def attribute(self, name: str) -> MappedColumn[Any]: ...
    def relationship(self, name: str) -> Relationship[Any]: ...

class Relationship(Generic[T]):
    foreign_key: str | tuple[str, ...] | None
    uselist: bool
    back_populates: str | None
    cascade: frozenset[str]
    secondary: Table | None
    passive_deletes: bool
    name: str | None
    def __init__(
        self,
        target: type[T] | str,
        *,
        foreign_key: str | tuple[str, ...] | None = None,
        uselist: bool = False,
        back_populates: str | None = None,
        cascade: str | Iterable[str] = (),
        secondary: Table | None = None,
        secondary_local_key: str | tuple[str, ...] | None = None,
        secondary_remote_key: str | tuple[str, ...] | None = None,
        passive_deletes: bool = False,
    ) -> None: ...
    @property
    def target(self) -> type[T]: ...
    @property
    def direction(self) -> str: ...
    @property
    def foreign_keys(self) -> tuple[str, ...]: ...
    @property
    def secondary_local_keys(self) -> tuple[str, ...]: ...
    @property
    def secondary_remote_keys(self) -> tuple[str, ...]: ...
    @overload
    def __get__(self, instance: None, owner: type | None = None) -> Relationship[T]: ...
    @overload
    def __get__(
        self, instance: object, owner: type | None = None
    ) -> T | None | MutableSequence[T]: ...
    def __set__(self, instance: object, value: T | None | Iterable[T]) -> None: ...

def relationship(
    target: type[T] | str,
    *,
    foreign_key: str | tuple[str, ...] | None = None,
    uselist: bool = False,
    back_populates: str | None = None,
    cascade: str | Iterable[str] = (),
    secondary: Table | None = None,
    secondary_local_key: str | tuple[str, ...] | None = None,
    secondary_remote_key: str | tuple[str, ...] | None = None,
    passive_deletes: bool = False,
) -> Relationship[T]: ...

class Registry:
    def __init__(self) -> None: ...
    def mapper_for(self, model: type[DeclarativeBase]) -> Mapper: ...
    def mappers(self) -> tuple[Mapper, ...]: ...
    def polymorphic_mapper(self, mapper: Mapper, identity: Any) -> Mapper: ...

mapper_registry: Registry

class OrmMetadata:
    def __init__(
        self,
        registry: Registry = ...,
        *,
        models: Iterable[type[DeclarativeBase]] | None = None,
    ) -> None: ...
    @property
    def mappers(self) -> tuple[Mapper, ...]: ...
    def ddl(self, provider: str, *, checkfirst: bool = False) -> tuple[str, ...]: ...
    def create_all(self, session: Any, *, checkfirst: bool = False) -> None: ...
    async def create_all_async(
        self, session: Any, *, checkfirst: bool = False
    ) -> None: ...
    def drop_all(self, session: Any, *, checkfirst: bool = True) -> None: ...
    async def drop_all_async(
        self, session: Any, *, checkfirst: bool = True
    ) -> None: ...

@dataclass(frozen=True, slots=True)
class Migration:
    revision: str
    down_revision: str | tuple[str, ...] | None
    upgrade: Any
    downgrade: Any | None = None
    checksum: str = ""
    def __post_init__(self) -> None: ...

class MigrationRunner:
    migrations: tuple[Migration, ...]
    def __init__(self, migrations: Iterable[Migration]) -> None: ...
    def apply(self, session: Any) -> tuple[str, ...]: ...
    def rollback(self, session: Any, *, steps: int = 1) -> tuple[str, ...]: ...
    def recover(
        self, session: Any, revision: str, *, assume_applied: bool = False
    ) -> None: ...

class AsyncMigrationRunner(MigrationRunner):
    async def apply(self, session: Any) -> tuple[str, ...]: ...  # type: ignore[override]
    async def rollback(  # type: ignore[override]
        self, session: Any, *, steps: int = 1
    ) -> tuple[str, ...]: ...
    async def recover(  # type: ignore[override]
        self, session: Any, revision: str, *, assume_applied: bool = False
    ) -> None: ...

class DeclarativeBase:
    __registry__: Registry
    __mapper__: Mapper | None
    __table__: Table
    def __init__(self, **values: Any) -> None: ...

@dataclass(frozen=True, slots=True)
class LoaderOption:
    relationship: Relationship[Any] | tuple[Relationship[Any], ...]
    strategy: str
    def __post_init__(self) -> None: ...

def selectinload(
    relation: Relationship[Any], *path: Relationship[Any]
) -> LoaderOption: ...
def joinedload(
    relation: Relationship[Any], *path: Relationship[Any]
) -> LoaderOption: ...

class OrmQuery(Generic[T]):
    def where(self, predicate: Predicate) -> OrmQuery[T]: ...
    def order_by(self, *values: Expression | Ordering) -> OrmQuery[T]: ...
    def limit(self, value: int) -> OrmQuery[T]: ...
    def offset(self, value: int) -> OrmQuery[T]: ...
    def distinct(self) -> OrmQuery[T]: ...
    def distinct_on(self, *expressions: Expression) -> OrmQuery[T]: ...
    def with_for_update(
        self, *relations: str | Table, strength: str = ...,
        nowait: bool = ..., skip_locked: bool = ...,
    ) -> OrmQuery[T]: ...
    def group_by(self, *expressions: Expression) -> OrmQuery[T]: ...
    def having(self, predicate: Predicate) -> OrmQuery[T]: ...
    def join(
        self,
        relation: str | Relationship[Any] | type[DeclarativeBase],
        on: Predicate | None = None,
        *,
        kind: str = "inner",
    ) -> OrmQuery[T]: ...
    def where_related(
        self,
        relation: str | Relationship[Any],
        predicate: Predicate,
        *,
        kind: str = "inner",
    ) -> OrmQuery[T]: ...
    def options(self, *loaders: LoaderOption) -> OrmQuery[T]: ...
    def project(self, *expressions: Expression) -> OrmRowsQuery: ...
    def with_entities(self, *models: type[DeclarativeBase]) -> OrmEntityTupleQuery: ...
    def all(self, parameters: Mapping[str, Any] | None = None) -> list[T]: ...
    def partitions(
        self, batch_size: int, parameters: Mapping[str, Any] | None = None,
        *, detach: bool = ...,
    ) -> Iterator[list[T]]: ...
    def stream(
        self, batch_size: int, parameters: Mapping[str, Any] | None = None,
        *, detach: bool = ...,
    ) -> Iterator[T]: ...
    def first(self, parameters: Mapping[str, Any] | None = None) -> T | None: ...
    def one(self, parameters: Mapping[str, Any] | None = None) -> T: ...
    def one_or_none(self, parameters: Mapping[str, Any] | None = None) -> T | None: ...
    def count(self, parameters: Mapping[str, Any] | None = None) -> int: ...
    def exists(self, parameters: Mapping[str, Any] | None = None) -> bool: ...
    def update(
        self,
        values: Mapping[str, Any],
        parameters: Mapping[str, Any] | None = None,
    ) -> int: ...
    def delete(self, parameters: Mapping[str, Any] | None = None) -> int: ...

class OrmSession:
    def __init__(
        self, session: Any, *, autoflush: bool = True, isolation: str | None = None,
        read_only: bool | None = None, statement_timeout_ms: int | None = None,
        context: Any | None = None, native_query_policy: str | None = None,
        insert_batch_size: int = 100,
        close_session: bool = False,
    ) -> None: ...
    @property
    def is_active(self) -> bool: ...
    def __enter__(self) -> OrmSession: ...  # noqa: PYI034
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def add(self, instance: DeclarativeBase) -> None: ...
    def add_all(self, instances: Iterable[DeclarativeBase]) -> None: ...
    def bulk_insert(
        self, model: type[DeclarativeBase], rows: Iterable[Mapping[str, Any]]
    ) -> int: ...
    def bulk_upsert(
        self, model: type[DeclarativeBase], rows: Iterable[Mapping[str, Any]], *,
        conflict_columns: Iterable[str],
        update_values: Mapping[str, Any] | None = None,
    ) -> int: ...
    def listen(self, event: str, callback: Any) -> None: ...
    def no_autoflush(self) -> Any: ...
    def query(self, model: type[T]) -> OrmQuery[T]: ...
    def get(self, model: type[T], identity: Any) -> T | None: ...
    def refresh(self, instance: DeclarativeBase) -> None: ...
    def load(
        self, instance: DeclarativeBase, relation: str | Relationship[T]
    ) -> T | None | MutableSequence[T]: ...
    def merge(self, instance: T, *, load: bool = True) -> T: ...
    def expunge(self, instance: DeclarativeBase) -> None: ...
    def expire(self, instance: DeclarativeBase, *attributes: str) -> None: ...
    def expire_all(self) -> None: ...
    def delete(self, instance: DeclarativeBase) -> None: ...
    def flush(self) -> None: ...
    def savepoint(self, name: str) -> None: ...
    def rollback_to_savepoint(self, name: str) -> None: ...
    def release_savepoint(self, name: str) -> None: ...
    def begin_nested(self, name: str) -> Any: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...

class AsyncOrmQuery(Generic[T]):
    def where(self, predicate: Predicate) -> AsyncOrmQuery[T]: ...
    def order_by(self, *values: Expression | Ordering) -> AsyncOrmQuery[T]: ...
    def limit(self, value: int) -> AsyncOrmQuery[T]: ...
    def offset(self, value: int) -> AsyncOrmQuery[T]: ...
    def distinct(self) -> AsyncOrmQuery[T]: ...
    def distinct_on(self, *expressions: Expression) -> AsyncOrmQuery[T]: ...
    def with_for_update(
        self, *relations: str | Table, strength: str = ...,
        nowait: bool = ..., skip_locked: bool = ...,
    ) -> AsyncOrmQuery[T]: ...
    def group_by(self, *expressions: Expression) -> AsyncOrmQuery[T]: ...
    def having(self, predicate: Predicate) -> AsyncOrmQuery[T]: ...
    def join(
        self,
        relation: str | Relationship[Any] | type[DeclarativeBase],
        on: Predicate | None = None,
        *,
        kind: str = "inner",
    ) -> AsyncOrmQuery[T]: ...
    def where_related(
        self,
        relation: str | Relationship[Any],
        predicate: Predicate,
        *,
        kind: str = "inner",
    ) -> AsyncOrmQuery[T]: ...
    def options(self, *loaders: LoaderOption) -> AsyncOrmQuery[T]: ...
    def project(self, *expressions: Expression) -> AsyncOrmRowsQuery: ...
    def with_entities(
        self, *models: type[DeclarativeBase]
    ) -> AsyncOrmEntityTupleQuery: ...
    async def all(self, parameters: Mapping[str, Any] | None = None) -> list[T]: ...
    async def partitions(
        self, batch_size: int, parameters: Mapping[str, Any] | None = None,
        *, detach: bool = ...,
    ) -> AsyncIterator[list[T]]: ...
    async def stream(
        self, batch_size: int, parameters: Mapping[str, Any] | None = None,
        *, detach: bool = ...,
    ) -> AsyncIterator[T]: ...
    async def first(self, parameters: Mapping[str, Any] | None = None) -> T | None: ...
    async def one(self, parameters: Mapping[str, Any] | None = None) -> T: ...
    async def one_or_none(
        self, parameters: Mapping[str, Any] | None = None
    ) -> T | None: ...
    async def count(self, parameters: Mapping[str, Any] | None = None) -> int: ...
    async def exists(self, parameters: Mapping[str, Any] | None = None) -> bool: ...
    async def update(
        self,
        values: Mapping[str, Any],
        parameters: Mapping[str, Any] | None = None,
    ) -> int: ...
    async def delete(self, parameters: Mapping[str, Any] | None = None) -> int: ...

class OrmRowsQuery:
    def where(self, predicate: Predicate) -> OrmRowsQuery: ...
    def order_by(self, *values: Expression | Ordering) -> OrmRowsQuery: ...
    def limit(self, value: int) -> OrmRowsQuery: ...
    def all(
        self, parameters: Mapping[str, Any] | None = None
    ) -> list[Mapping[str, Any]]: ...

class OrmEntityTupleQuery:
    def where(self, predicate: Predicate) -> OrmEntityTupleQuery: ...
    def order_by(self, *values: Expression | Ordering) -> OrmEntityTupleQuery: ...
    def limit(self, value: int) -> OrmEntityTupleQuery: ...
    def all(
        self, parameters: Mapping[str, Any] | None = None
    ) -> list[tuple[Any, ...]]: ...

class AsyncOrmRowsQuery:
    def where(self, predicate: Predicate) -> AsyncOrmRowsQuery: ...
    def order_by(self, *values: Expression | Ordering) -> AsyncOrmRowsQuery: ...
    def limit(self, value: int) -> AsyncOrmRowsQuery: ...
    async def all(
        self, parameters: Mapping[str, Any] | None = None
    ) -> list[Mapping[str, Any]]: ...

class AsyncOrmEntityTupleQuery:
    def where(self, predicate: Predicate) -> AsyncOrmEntityTupleQuery: ...
    def order_by(self, *values: Expression | Ordering) -> AsyncOrmEntityTupleQuery: ...
    def limit(self, value: int) -> AsyncOrmEntityTupleQuery: ...
    async def all(
        self, parameters: Mapping[str, Any] | None = None
    ) -> list[tuple[Any, ...]]: ...

class AsyncOrmSession:
    def __init__(
        self, session: Any, *, autoflush: bool = True, isolation: str | None = None,
        read_only: bool | None = None, statement_timeout_ms: int | None = None,
        context: Any | None = None, native_query_policy: str | None = None,
        insert_batch_size: int = 100,
        close_session: bool = False,
    ) -> None: ...
    @property
    def is_active(self) -> bool: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    async def __aenter__(self) -> AsyncOrmSession: ...  # noqa: PYI034
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def add(self, instance: DeclarativeBase) -> None: ...
    def add_all(self, instances: Iterable[DeclarativeBase]) -> None: ...
    async def bulk_insert(
        self, model: type[DeclarativeBase], rows: Iterable[Mapping[str, Any]]
    ) -> int: ...
    async def bulk_upsert(
        self, model: type[DeclarativeBase], rows: Iterable[Mapping[str, Any]], *,
        conflict_columns: Iterable[str],
        update_values: Mapping[str, Any] | None = None,
    ) -> int: ...
    def listen(self, event: str, callback: Any) -> None: ...
    def no_autoflush(self) -> Any: ...
    def query(self, model: type[T]) -> AsyncOrmQuery[T]: ...
    async def get(self, model: type[T], identity: Any) -> T | None: ...
    async def refresh(self, instance: DeclarativeBase) -> None: ...
    async def load(
        self, instance: DeclarativeBase, relation: str | Relationship[T]
    ) -> T | None | MutableSequence[T]: ...
    async def merge(self, instance: T, *, load: bool = True) -> T: ...
    def expunge(self, instance: DeclarativeBase) -> None: ...
    def expire(self, instance: DeclarativeBase, *attributes: str) -> None: ...
    def expire_all(self) -> None: ...
    def delete(self, instance: DeclarativeBase) -> None: ...
    async def flush(self) -> None: ...
    async def savepoint(self, name: str) -> None: ...
    async def rollback_to_savepoint(self, name: str) -> None: ...
    async def release_savepoint(self, name: str) -> None: ...
    def begin_nested(self, name: str) -> Any: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...

def inspect_instance(instance: DeclarativeBase) -> InstanceInspection: ...
