"""Type stubs per i builder portable AST (sync)."""
from typing import Any, Protocol, Self


class _PortableBackend(Protocol):
    """Session o Transaction — quello che i builder chiamano indietro."""

    def _execute_portable_rows(self, ast_json: str) -> list[dict]: ...
    def _execute_portable_count(self, ast_json: str) -> int: ...


class _WhereMixin:
    def __init__(self) -> None: ...
    def where_eq(self, column: str, value: Any) -> Self: ...
    def where_ne(self, column: str, value: Any) -> Self: ...
    def where_lt(self, column: str, value: Any) -> Self: ...
    def where_lte(self, column: str, value: Any) -> Self: ...
    def where_gt(self, column: str, value: Any) -> Self: ...
    def where_gte(self, column: str, value: Any) -> Self: ...
    def where_in(self, column: str, values: list) -> Self: ...
    def where_between(self, column: str, low: Any, high: Any) -> Self: ...
    def where_like(self, column: str, pattern: str) -> Self: ...
    def where_is_null(self, column: str) -> Self: ...
    def where_is_not_null(self, column: str) -> Self: ...
    def where_spatial(
        self,
        column: str,
        predicate: str,
        reference: Any,   # SpatialReference (evita import ciclo)
        distance_meters: float | None = None,
    ) -> Self: ...


class Select(_WhereMixin):
    def __init__(
        self, session: _PortableBackend, table: str, schema: str | None = None
    ) -> None: ...
    def columns(self, *cols: str) -> Self: ...
    def order_by(
        self, column: str, direction: str = "asc", nulls: str | None = None
    ) -> Self: ...
    def limit(self, n: int) -> Self: ...
    def to_ast(self) -> dict: ...
    def all(self) -> list[dict]: ...
    def one(self) -> dict | None: ...
    def scalar(self) -> Any: ...


class Insert:
    def __init__(
        self, session: _PortableBackend, table: str, schema: str | None = None
    ) -> None: ...
    def values(self, **kwargs: Any) -> Self: ...
    def rows(self, rows: list[dict]) -> Self: ...
    def returning(self, *cols: str) -> Self: ...
    def to_ast(self) -> dict: ...
    def execute(self) -> int: ...
    def all(self) -> list[dict]: ...
    def one(self) -> dict: ...


class Update(_WhereMixin):
    def __init__(
        self, session: _PortableBackend, table: str, schema: str | None = None
    ) -> None: ...
    def set(self, **kwargs: Any) -> Self: ...
    def returning(self, *cols: str) -> Self: ...
    def to_ast(self) -> dict: ...
    def execute(self) -> int: ...
    def all(self) -> list[dict]: ...
    def one(self) -> dict: ...


class Delete(_WhereMixin):
    def __init__(
        self, session: _PortableBackend, table: str, schema: str | None = None
    ) -> None: ...
    def returning(self, *cols: str) -> Self: ...
    def to_ast(self) -> dict: ...
    def execute(self) -> int: ...
    def all(self) -> list[dict]: ...
    def one(self) -> dict: ...


class Upsert:
    def __init__(
        self, session: _PortableBackend, table: str, schema: str | None = None
    ) -> None: ...
    def values(self, **kwargs: Any) -> Self: ...
    def rows(self, rows: list[dict]) -> Self: ...
    def conflict_target(self, *cols: str) -> Self: ...
    def update_on_conflict(self, **kwargs: Any) -> Self: ...
    def returning(self, *cols: str) -> Self: ...
    def to_ast(self) -> dict: ...
    def execute(self) -> int: ...
    def all(self) -> list[dict]: ...
    def one(self) -> dict: ...
