from typing import Any
from typing_extensions import Self

class InstrumentedEngine:
    def __init__(self, engine: Any, tracer: Any, meter: Any = None) -> None: ...
    def session(self) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *args: object) -> bool: ...

def instrument_engine(engine: Any, *, tracer: Any | None = None, meter: Any | None = None) -> InstrumentedEngine: ...
