"""Type stubs per i typed params helpers."""
from typing import Any


class TypedValue:
    def __init__(self, kind: str, value: Any) -> None: ...
    def __repr__(self) -> str: ...


def uuid(value: str) -> TypedValue: ...
def int32(value: int) -> TypedValue: ...
def int64(value: int) -> TypedValue: ...
def date(value: str) -> TypedValue: ...
def timestamp(value: str) -> TypedValue: ...
def timestamptz(value: str) -> TypedValue: ...
def decimal(value: str) -> TypedValue: ...
def null(type_name: str) -> TypedValue: ...
